# Generated by Django 6.1.1 on 2026-09-22 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_contacto_direccion'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo_orden', models.CharField(max_length=25, unique=True)),
                ('fecha_solicitud', models.DateField()),
                ('hora_generacion', models.TimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prioridad', models.CharField(max_length=30)),
                ('confirmado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_autorizacion', models.CharField(max_length=60)),
                ('fecha_emision', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=40)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('enviada_cliente', models.BooleanField(default=False)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordencompra')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('unidades', models.PositiveIntegerField()),
                ('descuento_aplicado', models.FloatField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ordencompra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
